### PR TITLE
Fixed videos opening in full screen by default on iOS

### PR DESCRIPTION
**Pull request by agadev**
Fixed videos opening in full screen by default on iOS

### CODE REVIEW

**Comment by jonatadashi** [comment]
Duplicate #411

**Comment by sarbagyastha** [comment]
Doing this might violate YouTube's policy. Have you tried publishing to AppStore with the changes you made?

**Comment by stillie** [comment]
Any update on this PR?

**Comment by wer-mathurin** [comment]
@sarbagyastha : Can you elaborate more on: "Doing this might violate YouTube's policy".

**Comment by sarbagyastha** [comment]
This should be fixed with v2.2.2

> Can you elaborate more on: "Doing this might violate YouTube's policy".
@wer-mathurin This PR removes the url override, which is responsible for navigating youtube links expect videos to YouTube itself. YouTube TOS mention that tapping on elements other than videos and it's controls should navigate to YouTube.

**Pull request closed without merging**
