### PR TITLE
Fixed the bugs, seems to work perfectly now.

### PR DESCRIPTION
**Pull request by sgehrman**
There were a few bugs.  I couldn't even run the demo previously, now it works perfectly.  Fullscreen works etc.

I linted the code with the latest recommendations.  

I'm using it in a sliverlist and it works fine if you scroll  up and down etc.  It didn't work at all before.

### CODE REVIEW

**Comment by sarbagyastha** [comment]
Thank you for the PR. Could you please address the comments.

**Comment by sgehrman** [comment]
I was wondering what this is for:

 onWebViewCreated: (webController) {
          _webController.complete(webController);
          _webController.future.then(

Why a completer?  I've seen this crash here a few times on hot reload and was going to remove it, but wanted to ask first.

**Comment by sarbagyastha** [comment]
It's to ensure that webview controller is assigned after webview is completely ready at native side.  On iOS, controller is null sometimes even on onWebViewCreated. But there's no such case in Android as per my experience.

**Comment by sgehrman** [comment]
> It's to ensure that webview controller is assigned after webview is completely ready at native side. On iOS, controller is null sometimes even on onWebViewCreated. But there's no such case in Android as per my experience.

Not sure how that would work.  I removed the completer before I saw your comment.  I'm on Android so I didn't test on iOS. Could you confirm that Completer actually does anything useful?  Or see if it just works now on iOS?

**Comment by sarbagyastha** [comment]
@sgehrman you may leave the completer as it was before, so that i can merge the PR. I'll test it on iOS later on regrading the completer.

**Comment by sgehrman** [comment]
> @sgehrman you may leave the completer as it was before, so that i can merge the PR. I'll test it on iOS later on regrading the completer.

The completer was crashing for me on Android.  I really don't think it serves any purpose. I don't see how it could have any positive effects.  I would merge and put back the completer if you want. It's only  a few lines of code.

**Comment by sarbagyastha** [comment]
@sgehrman Completer is also used in the example app for [webview_flutter.](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/example/lib/main.dart)

**Comment by sgehrman** [comment]
> @sgehrman Completer is also used in the example app for [webview_flutter.](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/example/lib/main.dart)

Looks like in that sample app the completer is being used for something useful.

          NavigationControls(_controller.future),
          SampleMenu(_controller.future),

When the webviewController is ready, it calls the completer and the NavigationControls and SampleMenu can use it, but in your code it wasn't doing anything useful like that. 

It was getting the webviewController and then calling complete, but the next line was the code to set the webviewController to the controller.

controller.updateValue(	
                controller.value.copyWith(webViewController: webViewController),	
              );

So I still don't think it's needed, and I wouldn't mind putting it back if it was harmless, but I was seeing hotreload errors on the complete.

**Pull request merged**
