### PR TITLE
Migration for inappwebview 6.x.x

### PR DESCRIPTION
**Pull request by mdalameen**

### CODE REVIEW

**Comment by marciorr** [comment]
Any idea when this will be merged?

**Comment by DavidOrakpo** [comment]
Please Merge, or someone should fork this repo with the fixes implemented

**Comment by pumano** [comment]
Would be good to have it

**Comment by marciorr** [comment]
Nothing yet? This would be gratefully appreciated.

**Comment by sarbagyastha** [comment]
Published [v9.0.0-beta.0](https://pub.dev/packages/youtube_player_flutter/versions/9.0.0-beta.0)

**Pull request merged**
