### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by sarbagyastha**
Implementation of https://github.com/sarbagyastha/youtube_player_flutter/discussions/647

### CODE REVIEW

**Comment by mark8044** [comment]
**Videos play fine with iOS.**
**On Android, videos fail to load/play.**  They show a standard YouTube error: 
"An error occurred.  Please try again later (Playback ID: ....). Learn More"

If you click on Learn More it just takes you to a YouTube Help Center for troubleshooting video playback errors

Code used to load the video:

```
class _YoutubeWidgetState extends State<_YoutubeWidget> {

      YoutubePlayerController controller = YoutubePlayerController(
      params: const YoutubePlayerParams(
          showControls: true,
          showFullscreenButton: true,
      ),
    );

  @override
  initState()
  {
    super.initState();
    controller.cueVideoById(videoId: widget.videoId);
  }

  @override
  dispose()
  {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return YoutubePlayerIFrame(
      controller: controller,
      aspectRatio: 16 / 9,
    );
  }
}
```

**Comment by sarbagyastha** [comment]
@mark8044 Can you please provide the videoID that you're using ?

**Comment by mark8044** [comment]
> @mark8044 Can you please provide the videoID that you're using ?

@sarbagyastha It happens with any videoid, for example: `Z6KZ3cTGBWw`

**Comment by cyb3rsalih** [comment]
I want to include the package to my project  , but getting error
`pub get failed (1; Could not find a file named "pubspec.yaml" in`


```
youtube_player_flutter_v3:
    git:
      url: https://github.com/sarbagyastha/youtube_player_flutter.git
      ref: v3 # branch name 
```

**Pull request merged**
