### PR TITLE
Add the event only if the controller is not closed

### LINKED ISSUE #828: [BUG] Getting Cannot add new events after calling close error
**Describe the bug**
When I call the close method of the controller I got that error.
```
@override
  void dispose() {
    _playerStateSubscription.cancel();
    _positionSubscription.cancel();
    _controller.close();
    super.dispose();
  }
```
**To Reproduce**
Call the close method on the dispose

**Additional context**
I see that this issue was reported a long time ago (#782) but the pull request that fixes  the issue is not merged (#730). Why??

### LINKED ISSUE #864: Unhandled Exception: Bad state: Cannot add new events after calling close
when i tried close the controller in dispose  i am getting this error  Unhandled Exception: Bad state: Cannot add new events after calling close

import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:lhtv/Api/Api.dart';
import 'package:youtube_player_iframe/youtube_player_iframe.dart';

import '../Models/Slidermodel.dart';

class Livestream extends StatefulWidget {

  @override
  State<Livestream> createState() => _LivestreamState();

}

class _LivestreamState extends State<Livestream> {
  late YoutubePlayerController _controller;

  @override
  void initState() {
    super.initState();

    _controller = YoutubePlayerController(
      params: const YoutubePlayerParams(
        showControls: true,
        mute: false,
        showFullscreenButton: true,
        loop: false,
      ),
    );

    _controller.setFullScreenListener((isFullScreen) {
      if (isFullScreen) {
        // Do something when entering full-screen mode
      } else {
        // Do something when exiting full-screen mode
      }
    });
  }

  @override
  void dispose() {
    super.dispose();
    _controller.close();
    print('Close');
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: FutureBuilder<Model?>(
          future: Api().livestream(17),
          builder: (BuildContext context, AsyncSnapshot<Model?> snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return Center(child: CircularProgressIndicator());
            } else if (snapshot.hasError || snapshot.data == null) {
              return Text('Error fetching data');
            }
            else {
              String videoId = snapshot.data!.nEWSAPP![0].videoId!;

              _controller = YoutubePlayerController.fromVideoId(
                videoId: '${videoId}',
                autoPlay: true,
                params: const YoutubePlayerParams(showFullscreenButton: true),
              );

              return YoutubePlayerScaffold(
                controller: _controller,
                aspectRatio: 16 / 9,
                builder: (context, player) {
                  return SingleChildScrollView(
                    child: Column(
                      children: [
                        player,
                        Text(
                          snapshot.data!.nEWSAPP![0].newsTitle!,
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                          ),
                        ),
                        SizedBox(height: 10),
                        Text(snapshot.data!.nEWSAPP![0].newsDescription!),
                      ],
                    ),
                  );
                },
              );
            }
          },
        ),
      ),
    );
  }
}

### PR DESCRIPTION
**Pull request by deepak786**
fixes https://github.com/sarbagyastha/youtube_player_flutter/issues/300
fixes https://github.com/sarbagyastha/youtube_player_flutter/issues/782
fixes #864
fixes #828

### CODE REVIEW

**Comment by deepak-agendaboa** [comment]
@sarbagyastha Can you please check and merge this?

**Comment by EArminjon** [comment]
@sarbagyastha please :'(

**Comment by Y-ndm** [comment]
@sarbagyastha this needs to be fixed ASAP.

**Comment by FaisalMohammadi** [comment]
yes please merge this pull request i am also facing the same error in Amdroid.

**Comment by FaisalMohammadi** [comment]
it is now since almost 1 year why is not merged please merge this. I am getting the same error.

**Comment by NicolasEymael** [comment]
@sarbagyastha any news on this?

**Comment by FaisalMohammadi** [comment]
any update opn this pull requst?

**Comment by svarup** [comment]
+1

**Comment by aabhas-irex** [comment]
+1

**Comment by Jaaco** [comment]
+1

**Comment by kirannonstop** [comment]
Any update on this @sarbagyastha ? Same issue I am facing.

**Comment by chillbrodev** [comment]
Could we get this merged and released? This bug is plaguing my Sentry. It's a year and a half old.

**Comment by ConnorDykes** [comment]
can we please merge this? the issue is still there

**Comment by chillbrodev** [comment]
@sarbagyastha Bumping this. If possible could you please review and merge?

**Comment by sarbagyastha** [comment]
Fixed with `youtube_player_iframe: ^5.1.4`

**Comment by chillbrodev** [comment]
> Fixed with `youtube_player_iframe: ^5.1.4`

Woo! Thank you!

**Pull request closed without merging**
